name: Deploy to xserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # 適切なPythonバージョンに変更

      - name: Install dependencies
        run: pip install -r requirements.txt  # requirements.txtに依存ライブラリを記述します

      - name: ssh key generate
        run: |
          echo "$SSH_PRIVATE_KEY" > key
          chmod 600 key
          cat key  # デバッグのために秘密鍵を表示
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH Connection
        run: |
          ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022 xs739875@sv14591.xserver.jp "echo 'SSH Connection Successful'"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to xserver
        run: |
          # デプロイコマンドを実行します。以下は一般的な例です。実際のコマンドに置き換えてください。
          ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022 -vvv xs739875@sv14591.xserver.jp "cd /home/xs739875/xs739875.xsrv.jp/public_html/API && git pull origin main && systemctl restart Rest-API" 2>&1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  

